specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_package_name: fmf
downstream_package_name: fmf

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9

  - job: tests
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9

  - job: copr_build
    trigger: commit
    branch: main
    targets:
    - fedora-all
    - epel-9
    list_on_homepage: True
    preserve_project: True
    owner: "@teemtee"
    project: fmf
