specfile_path: fmf.spec
files_to_sync:
  - fmf.spec
  - .packit.yaml

upstream_package_name: fmf
downstream_package_name: fmf

upstream_project_url: https://github.com/teemtee/fmf
issue_repository: https://github.com/teemtee/fmf

targets: &all-targets
  - fedora-all
  - epel-9

jobs:
  - &copr_build
    job: copr_build
    trigger: pull_request

  - &tests
    job: tests
    trigger: pull_request

  - <<: *copr_build
    trigger: commit
    branch: main
    list_on_homepage: True
    preserve_project: True
    owner: "@teemtee"
    project: fmf

  # Fedora releases
  - job: propose_downstream
    trigger: release
    dist_git_branches: *all-targets

  - job: koji_build
    trigger: commit
    dist_git_branches: *all-targets

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
      - epel-9
